format = """
[â–‘â–’â–“](#a3aed2)\
[ ï…¼ ](bg:#a3aed2 fg:#090c0c)\
$sudo\
[î˜‚](bg:#c9cbff fg:#a3aed2)\
$username\
$hostname\
$directory\
[î˜‚](fg:#c9cbff bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#2e374c)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#2e374c bg:#6c7086)\
$time\
[î‚´](fg:#6c7086)\
\n$character\
"""

right_format="""
[î‚¶](fg:#c9cbff bg:transparent)\
$status\
[î‚´](fg:#c9cbff bg:transparent) \
"""
add_newline = false


[username]
style_user = 'fg:#4c4f69 bg:#c9cbff'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[@$hostname:](fg:#4c4f69 bg:#c9cbff)'
trim_at = '.'
ssh_symbol = 'ğŸŒ'
disabled = false

[sudo]
format ='[$symbol]($style)'
style = 'bg:#a3aed2 fg:#090c0c'
symbol = 'ó°šŒ '
disabled = false

[directory]
style = "fg:#4c4f69 bg:#c9cbff"
before_repo_root_style = "fg:#4c4f69 bg:#c9cbff"
repo_root_style="fg:#4c4f69 bg:#c9cbff"
read_only= "ğŸ”"
read_only_style= "bg:#f38ba8"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format="[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ï‚› ]($style)[$read_only]($read_only_style)"
truncation_length = 6
truncation_symbol = "â€¦/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°½° "
"Pictures" = "ï€¾ "


[git_branch]
symbol = "ó°˜¬"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#c9cbff bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#c9cbff bg:#394260)]($style)'
#added by me
conflicted = ' ğŸ³ '
ahead = 'ğŸğŸ’¨â‡¡${count}'
behind = 'ğŸ˜°â‡£${count}'
diverged = 'ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = 'âœ“'
untracked = ' ğŸ¤· '
stashed = ' ğŸ“¦ '
modified = ' ğŸ“ '
staged = '[++\($count\)](green)'
renamed = ' ğŸ‘… '
deleted = ' ğŸ—‘ '

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[time]
disabled = false
time_format = "%A %d %b %I:%M %P" # Hour:Minute Format
style = "bg:#6c7086"
format = '[[  $time ](fg:#a0a9cb bg:#6c7086)]($style)'

[status]
style = 'fg:#4c4f69 bg:#c9cbff'
symbol = 'îª‡'
success_symbol = 'î®¤'
format = '[ $symbol $common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false
