format = """
[â–‘â–’â–“](#a8876c)\
[ ï…¼ ](bg:#a8876c fg:#f1c19b)\
$sudo\
[î˜‚](bg:#f1c19b fg:#a8876c)\
$username\
$hostname\
$directory\
[î˜‚](fg:#f1c19b bg:#CF8950)\
$git_branch\
$git_status\
[î‚´](fg:#CF8950 bg:#AF7445)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#AF7445 bg:#8D603C)\
$time\
[î‚´](fg:#8D603C)\
\n$character\
"""

right_format="""
[î‚¶](fg:#f1c19b bg:transparent)\
$status\
[î‚´](fg:#f1c19b bg:transparent)\
"""
add_newline = false

[character]
#success_symbol = '[â¯](#00ff00) '
#error_symbol = '[â¯](#ff0000)'
success_symbol = '[â¯](#f1c19b)'
error_symbol = '[â¯](#ff0000)'

[username]
style_user = 'fg:#976742 bg:#f1c19b'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[@$hostname:](fg:#976742 bg:#f1c19b)'
trim_at = '.'
ssh_symbol = 'ó°£€'
disabled = false

[sudo]
format ='[$symbol]($style)'
style = 'bg:#a8876c fg:#f1c19b'
symbol = 'ó°šŒ '
disabled = false

[directory]
style = "fg:#976742 bg:#f1c19b"
before_repo_root_style = "fg:#976742 bg:#f1c19b"
repo_root_style="fg:#976742 bg:#f1c19b"
read_only= "ó°‰‘"
read_only_style= "bg:#BE804D"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format="[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ï‚› ]($style)[$read_only]($read_only_style)"
truncation_length = 6
truncation_symbol = "â€¦/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°½° "
"Pictures" = "ï€¾ "


[git_branch]
symbol = "ó°˜¬"
style = "bg:#CF8950"
format = '[[ $symbol $branch ](fg:#f1c19b bg:#CF8950)]($style)'

[git_status]
style = "bg:#CF8950"
format = '[[($all_status$ahead_behind )](fg:#f1c19b bg:#CF8950)]($style)'
#added by me
conflicted = ' ğŸ³ '
ahead = 'ó°µµğŸ â‡¡${count}'
behind = 'ó°±¬ â‡£${count}'
diverged = 'ó°š› â‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = ' âœ“ '
untracked = ' î™¨ '
stashed = ' ğŸ“¦ '
modified = ' ó°·‰ '
staged = '[++\($count\)](green)'
renamed = ' ó°‡¹ '
deleted = ' ğŸ—‘ '

[nodejs]
symbol = "îœ˜"
style = "bg:#AF7445"
format = '[[ $symbol ($version) ](fg:#f1c19b bg:#AF7445)]($style)'

[rust]
symbol = "î¨"
style = "bg:#AF7445"
format = '[[ $symbol ($version) ](fg:#f1c19b bg:#AF7445)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#AF7445"
format = '[[ $symbol ($version) ](fg:#f1c19b bg:#AF7445)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#AF7445"
format = '[[ $symbol ($version) ](fg:#f1c19b bg:#AF7445)]($style)'

[time]
disabled = false
time_format = "%A %d %b %I:%M %P" # Hour:Minute Format
style = "bg:#8D603C"
format = '[[  $time ](fg:#CF8950 bg:#8D603C)]($style)'

[status]
style = 'fg:#976742 bg:#f1c19b'
symbol = 'îª‡'
success_symbol = 'î®¤'
format = '[ $symbol $common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false
